#include "french-compound-map.h"

namespace moonshine_tts::french_compound_map {

const std::unordered_map<std::string, std::string>& cardinal_compound_ipa_entries() {
  static const std::unordered_map<std::string, std::string> kMap = {
      {"cinquante", "sɛ̃kˈɑ̃t"},
      {"cinquante-cinq", "sɛ̃kˈɑ̃tsˈɛ̃k"},
      {"cinquante-deux", "sɛ̃kˈɑ̃tdˈø"},
      {"cinquante-et-un", "sɛ̃kˈɑ̃teˈœ̃"},
      {"cinquante-huit", "sɛ̃kˈɑ̃tyˈit"},
      {"cinquante-neuf", "sɛ̃kˈɑ̃tnˈœf"},
      {"cinquante-quatre", "sɛ̃kˈɑ̃tkˈatʁ"},
      {"cinquante-sept", "sɛ̃kˈɑ̃tsˈɛt"},
      {"cinquante-six", "sɛ̃kˈɑ̃tsˈis"},
      {"cinquante-trois", "sɛ̃kˈɑ̃ttʁwˈa"},
      {"dix-huit", "dˈizyˈit"},
      {"dix-neuf", "dˈiznˈœf"},
      {"dix-sept", "dˈisˈɛt"},
      {"quarante", "kaʁˈɑ̃t"},
      {"quarante-cinq", "kaʁˈɑ̃tsˈɛ̃k"},
      {"quarante-deux", "kaʁˈɑ̃tdˈø"},
      {"quarante-et-un", "kaʁˈɑ̃teˈœ̃"},
      {"quarante-huit", "kaʁˈɑ̃tyˈit"},
      {"quarante-neuf", "kaʁˈɑ̃tnˈœf"},
      {"quarante-quatre", "kaʁˈɑ̃tkˈatʁ"},
      {"quarante-sept", "kaʁˈɑ̃tsˈɛt"},
      {"quarante-six", "kaʁˈɑ̃tsˈis"},
      {"quarante-trois", "kaʁˈɑ̃ttʁwˈa"},
      {"quatre-vingt-cinq", "kˈatʁvˈɛ̃tsˈɛ̃k"},
      {"quatre-vingt-deux", "kˈatʁvˈɛ̃tdˈø"},
      {"quatre-vingt-dix", "kˈatʁvˈɛ̃dˈis"},
      {"quatre-vingt-dix-huit", "kˈatʁvˈɛ̃dˈizyˈit"},
      {"quatre-vingt-dix-neuf", "kˈatʁvˈɛ̃dˈiznˈœf"},
      {"quatre-vingt-dix-sept", "kˈatʁvˈɛ̃dˈisˈɛt"},
      {"quatre-vingt-douze", "kˈatʁvˈɛ̃dˈuz"},
      {"quatre-vingt-huit", "kˈatʁvˈɛ̃tyˈit"},
      {"quatre-vingt-neuf", "kˈatʁvˈɛ̃tnˈœf"},
      {"quatre-vingt-onze", "kˈatʁvˈɛ̃tˈɔ̃z"},
      {"quatre-vingt-quatorze", "kˈatʁvˈɛ̃katˈɔʁz"},
      {"quatre-vingt-quatre", "kˈatʁvˈɛ̃tkˈatʁ"},
      {"quatre-vingt-quinze", "kˈatʁvˈɛ̃kˈɛ̃z"},
      {"quatre-vingt-seize", "kˈatʁvˈɛ̃sˈɛz"},
      {"quatre-vingt-sept", "kˈatʁvˈɛ̃tsˈɛt"},
      {"quatre-vingt-six", "kˈatʁvˈɛ̃tsˈis"},
      {"quatre-vingt-treize", "kˈatʁvˈɛ̃tʁˈɛz"},
      {"quatre-vingt-trois", "kˈatʁvˈɛ̃ttʁwˈa"},
      {"quatre-vingt-un", "kˈatʁvˈɛ̃ˈœ̃"},
      {"quatre-vingts", "kˈatʁvˈɛ̃"},
      {"soixante-cinq", "swasˈɑ̃tsˈɛ̃k"},
      {"soixante-deux", "swasˈɑ̃tdˈø"},
      {"soixante-dix", "swasˈɑ̃tdˈis"},
      {"soixante-dix-huit", "swasˈɑ̃tdˈizyˈit"},
      {"soixante-dix-neuf", "swasˈɑ̃tdˈiznˈœf"},
      {"soixante-dix-sept", "swasˈɑ̃tdˈisˈɛt"},
      {"soixante-douze", "swasˈɑ̃tdˈuz"},
      {"soixante-et-onze", "swasˈɑ̃teˈɔ̃z"},
      {"soixante-huit", "swasˈɑ̃tyˈit"},
      {"soixante-neuf", "swasˈɑ̃tnˈœf"},
      {"soixante-onze", "swasˈɑ̃tˈɔ̃z"},
      {"soixante-quatorze", "swasˈɑ̃tkatˈɔʁz"},
      {"soixante-quatre", "swasˈɑ̃tkˈatʁ"},
      {"soixante-quinze", "swasˈɑ̃tkˈɛ̃z"},
      {"soixante-seize", "swasˈɑ̃tsˈɛz"},
      {"soixante-sept", "swasˈɑ̃tsˈɛt"},
      {"soixante-six", "swasˈɑ̃tsˈis"},
      {"soixante-treize", "swasˈɑ̃ttʁˈɛz"},
      {"soixante-trois", "swasˈɑ̃ttʁwˈa"},
      {"soixante-un", "swasˈɑ̃tˈœ̃"},
      {"trente", "tʁˈɑ̃t"},
      {"trente-cinq", "tʁˈɑ̃tsˈɛ̃k"},
      {"trente-deux", "tʁˈɑ̃tdˈø"},
      {"trente-et-un", "tʁˈɑ̃teˈœ̃"},
      {"trente-huit", "tʁˈɑ̃tyˈit"},
      {"trente-neuf", "tʁˈɑ̃tnˈœf"},
      {"trente-quatre", "tʁˈɑ̃tkˈatʁ"},
      {"trente-sept", "tʁˈɑ̃tsˈɛt"},
      {"trente-six", "tʁˈɑ̃tsˈis"},
      {"trente-trois", "tʁˈɑ̃ttʁwˈa"},
      {"vingt", "vˈɛ̃"},
      {"vingt-cinq", "vˈɛ̃tsˈɛ̃k"},
      {"vingt-deux", "vˈɛ̃tdˈø"},
      {"vingt-et-un", "vˈɛ̃teˈœ̃"},
      {"vingt-huit", "vˈɛ̃tyˈit"},
      {"vingt-neuf", "vˈɛ̃tnˈœf"},
      {"vingt-quatre", "vˈɛ̃tkˈatʁ"},
      {"vingt-sept", "vˈɛ̃tsˈɛt"},
      {"vingt-six", "vˈɛ̃tsˈis"},
      {"vingt-trois", "vˈɛ̃ttʁwˈa"},
  };
  return kMap;
}

}  // namespace moonshine_tts::french_compound_map
